document.addEventListener('DOMContentLoaded',function(){
var t=document.getElementById('navToggle'),m=document.getElementById('navMenu');if(t&&m)t.addEventListener('click',function(){m.classList.toggle('open')});
var b=document.getElementById('backToTop');if(b){window.addEventListener('scroll',function(){b.classList.toggle('visible',scrollY>300)});b.addEventListener('click',function(){scrollTo({top:0,behavior:'smooth'})})}
var p=(location.pathname.split('/').pop()||'index.html').replace('.html','');if(p==='index')p='dashboard';else if(p!=='events'&&p!=='checklist'&&p!=='participants')p='dashboard';
if(p==='events')!function(){
var fb=document.querySelectorAll('.filter-btn'),ec=document.querySelectorAll('.event-card'),cnt=document.getElementById('eventCount'),si=document.getElementById('eventSearchInput');
var ed={1:{title:'Konferencja Technologiczna 2026',type:'Konferencja',date:'15 lipca 2026',location:'Warszawa, Centrum Kongresowe',desc:'Największe wydarzenie branżowe roku. Prelekcje, warsztaty i networking z liderami technologii.',participants:120,status:'Aktywne',agenda:'10:00 - Rejestracja\n11:00 - Prelekcja główna\n13:00 - Lunch\n14:00 - Warsztaty\n17:00 - Networking'},2:{title:'Warsztaty z React 19',type:'Warsztaty',date:'22 sierpnia 2026',location:'Kraków, Makerspace',desc:'Praktyczne warsztaty z budowania nowoczesnych aplikacji webowych.',participants:30,status:'Aktywne',agenda:'09:00 - Wprowadzenie\n10:00 - Część praktyczna\n12:00 - Lunch\n13:00 - Projekt zespołowy\n16:00 - Prezentacja wyników'},3:{title:'Hackathon Weekend',type:'Hackathon',date:'5 września 2026',location:'Wrocław, Park Technologiczny',desc:'48-godzinny maraton programowania dla zespołów.',participants:60,status:'Aktywne',agenda:'Piątek 18:00 - Rozpoczęcie\nSobota - Całodniowe kodowanie\nNiedziela 16:00 - Prezentacje\n18:00 - Rozdanie nagród'},4:{title:'Spotkanie DevOps',type:'Meetup',date:'12 października 2026',location:'Gdańsk, Inkubator Startupów',desc:'Cykl spotkań dla pasjonatów DevOps. Temat: Kubernetes w praktyce.',participants:25,status:'Planowane',agenda:'17:00 - Wstęp\n17:30 - Prezentacja: Kubernetes w produkcji\n18:30 - Dyskusja\n19:00 - Pizza & networking'}};
function fe(){var af=document.querySelector('.filter-btn.active'),fv=af?af.dataset.filter:'all',st=si?si.value.toLowerCase():'',vc=0;ec.forEach(function(c){var s=c.dataset.status,t=c.querySelector('h3').textContent.toLowerCase(),d=c.querySelector('.event-desc').textContent.toLowerCase();c.classList.toggle('hidden',!((fv==='all'||s===fv)&&(t.indexOf(st)!==-1||d.indexOf(st)!==-1)));if(!c.classList.contains('hidden'))vc++});if(cnt)cnt.textContent=vc}
fb.forEach(function(b){b.addEventListener('click',function(){fb.forEach(function(x){x.classList.remove('active')});this.classList.add('active');fe()})});if(si)si.addEventListener('input',fe);
var mo=document.getElementById('eventModal'),mb=document.getElementById('modalBody'),mc=document.querySelector('.modal-close');
ec.forEach(function(c){c.addEventListener('click',function(){var id=this.dataset.eventId,e=ed[id];if(e&&mo&&mb){mb.innerHTML='<h3>'+e.title+'</h3><p><strong>Typ:</strong> '+e.type+'</p><p><strong>Data:</strong> '+e.date+'</p><p><strong>Miejsce:</strong> '+e.location+'</p><p>'+e.desc+'</p><p><strong>Uczestnicy:</strong> '+e.participants+'</p><p><strong>Status:</strong> <span class="event-status '+(e.status==='Aktywne'?'active':'planned')+'">'+e.status+'</span></p><hr><h4>Agenda</h4><pre class="agenda">'+e.agenda+'</pre>';mo.classList.add('open')}})});
if(mc&&mo){mc.addEventListener('click',function(){mo.classList.remove('open')});mo.addEventListener('click',function(e){if(e.target===mo)mo.classList.remove('open')})}}();
if(p==='checklist')!function(){
function sc(){var a=[];document.querySelectorAll('.checklist-items li').forEach(function(l){var c=l.querySelector('.check-item'),s=l.querySelector('.task-text');if(c&&s)a.push({text:s.textContent.trim(),checked:c.checked,category:(l.closest('.checklist-items')||{}).dataset.category||''})});localStorage.setItem('eventmanager_checklist',JSON.stringify(a))}
function lc(){var s=localStorage.getItem('eventmanager_checklist');if(!s)return;try{JSON.parse(s).forEach(function(x){document.querySelectorAll('.checklist-items').forEach(function(u){if(u.dataset.category===x.category){u.querySelectorAll('li').forEach(function(l){var s=l.querySelector('.task-text');if(s&&s.textContent.trim()===x.text){var c=l.querySelector('.check-item');if(c)c.checked=x.checked}})}})})}catch(e){}}
function up(){var c=document.querySelectorAll('.check-item'),t=c.length,k=document.querySelectorAll('.check-item:checked').length,p=t>0?(k/t)*100:0;var f=document.getElementById('progressFill'),n=document.getElementById('progressCount');if(f)f.style.width=p+'%';if(n)n.textContent=k+'/'+t;document.querySelectorAll('.checklist-items').forEach(function(u){var id={Organizacja:'orgCount',Promocja:'promCount',Technika:'techCount'}[u.dataset.category],c2=u.querySelectorAll('.check-item:checked').length;if(id)document.getElementById(id).textContent='('+c2+'/'+u.querySelectorAll('li').length+')'});sc()}
document.querySelectorAll('.check-item').forEach(function(c){c.addEventListener('change',up)});lc();up();
var ab=document.getElementById('addTaskBtn');if(ab)ab.addEventListener('click',function(){var t=prompt('Wpisz nazwę nowego zadania:');if(t&&t.trim()){var f=document.querySelector('.checklist-items');if(f){var l=document.createElement('li');l.innerHTML='<label><input type="checkbox" class="check-item"><span class="task-text">'+t.trim()+'</span></label><button class="delete-task" title="Usuń">&times;</button>';f.appendChild(l);l.querySelector('.check-item').addEventListener('change',up);l.querySelector('.delete-task').addEventListener('click',function(){l.remove();up()});up()}}});
document.querySelectorAll('.delete-task').forEach(function(b){b.addEventListener('click',function(){this.closest('li').remove();up()})})}();
if(p==='participants')!function(){
var si=document.getElementById('participantSearch'),rf=document.getElementById('roleFilter'),pc=document.querySelectorAll('.participant-card'),cnt=document.getElementById('participantCount');
function fp(){var st=si?si.value.toLowerCase():'',rv=rf?rf.value:'all',v=0;pc.forEach(function(c){var n=c.querySelector('h3').textContent.toLowerCase(),e=c.querySelector('.participant-email').textContent.toLowerCase(),co=c.querySelector('.participant-company').textContent.toLowerCase(),r=c.dataset.role,show=(n.indexOf(st)!==-1||e.indexOf(st)!==-1||co.indexOf(st)!==-1)&&(rv==='all'||r===rv);c.style.display=show?'flex':'none';if(show)v++});if(cnt)cnt.textContent=v}
if(si)si.addEventListener('input',fp);if(rf)rf.addEventListener('change',fp);
var ab=document.getElementById('addParticipantBtn'),mo=document.getElementById('addParticipantModal'),mc=mo?mo.querySelector('.modal-close'):null,f=document.getElementById('addParticipantForm');
if(ab&&mo)ab.addEventListener('click',function(){mo.classList.add('open')});
if(mc&&mo){mc.addEventListener('click',function(){mo.classList.remove('open')});mo.addEventListener('click',function(e){if(e.target===mo)mo.classList.remove('open')})}
if(f)f.addEventListener('submit',function(e){e.preventDefault();var nm=document.getElementById('pName'),em=document.getElementById('pEmail'),co=document.getElementById('pCompany'),rl=document.getElementById('pRole'),ok=true;document.querySelectorAll('.form-error').forEach(function(e){e.textContent=''});document.querySelectorAll('.form-input').forEach(function(e){e.classList.remove('error')});if(!nm.value.trim()){nm.classList.add('error');nm.closest('.form-group').querySelector('.form-error').textContent='Imię i nazwisko jest wymagane';ok=false}if(!em.value.trim()){em.classList.add('error');em.closest('.form-group').querySelector('.form-error').textContent='Adres e-mail jest wymagany';ok=false}else if(!/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(em.value)){em.classList.add('error');em.closest('.form-group').querySelector('.form-error').textContent='Podaj prawidłowy adres e-mail';ok=false}if(!rl.value){rl.classList.add('error');rl.closest('.form-group').querySelector('.form-error').textContent='Rola jest wymagana';ok=false}if(!ok)return;
var g=document.getElementById('participantsGrid');if(g){var inits=nm.value.split(' ').map(function(n){return n[0]}).join('').toUpperCase().substring(0,2),rlbl={prelegent:'Prelegent',uczestnik:'Uczestnik',organizator:'Organizator',sponsor:'Sponsor'},rcls={prelegent:'speaker',uczestnik:'attendee',organizator:'organizer',sponsor:'sponsor'},card=document.createElement('article');card.className='participant-card';card.dataset.role=rl.value;card.innerHTML='<div class="participant-avatar"><span class="avatar-initials">'+inits+'</span></div><div class="participant-info"><h3>'+nm.value.trim()+'</h3><p class="participant-email">'+em.value.trim()+'</p><p class="participant-company">'+(co.value.trim()||'Brak')+'</p><span class="participant-role '+rcls[rl.value]+'">'+rlbl[rl.value]+'</span></div>';g.appendChild(card);pc=document.querySelectorAll('.participant-card');if(cnt)cnt.textContent=pc.length}f.reset();mo.classList.remove('open')})}();
if(p==='dashboard')!function(){var s=localStorage.getItem('eventmanager_checklist');if(s)try{var a=JSON.parse(s),p=a.length>0?Math.round((a.filter(function(x){return x.checked}).length/a.length)*100):0,e=document.getElementById('dashProgress');if(e)e.textContent=p+'%'}catch(e){}}();
});
